defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra logging
hydra:
  output_subdir: null
  run:
    dir: .

# wandb config
wandb:
    entity: ramanakshay-personal
    project: continual-learning
    name: full-test
    mode: online

# system
system:
    seed: 42

# continual world config
environment:
    seq: cw10
    randomization: random_init_all
    normalize_reward: True

agent:
    type: random

algorithm:
    ## Trainer ##
    max_steps: 1000000
    # replay buffer
    buffer_size: 1000000
    batch_size: 256
    start_training: 10000
    train_interval: 1
    train_updates: 1
    ## Evaluator ##
    eval_interval: 20000
    eval_episodes: 10




