defaults:
  - _self_
  - agent: cotasp
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra logging
hydra:
  output_subdir: null
  run:
    dir: .

# wandb config
wandb:
    entity: embodied-learning-course-project
    project: continual-learning
    name: cotasp_final_small
    mode: online

# system
system:
    seed: 42

# continual world config
environment:
    seq: cw10
    randomization: deterministic
    normalize_reward: False

# replay buffer
data:
    buffer_size: ${algorithm.max_steps}
    batch_size: 256

# trainer
algorithm:
    max_steps: 1000000
    # training
    start_training: 10000
    train_interval: 1
    train_updates: 1
    # evaluation
    eval_interval: 20000
    eval_episodes: 10




